export const displayStyles = {
  displayNone: "hidden",
  displayBlock: "block",
  displayInline: "inline",
  displayInlineBlock: "inline-block",
  displayFlex: "flex",
  displayInlineFlex: "inline-flex",
  displayGrid: "grid",
  displayInlineGrid: "inline-grid",
  displayTable: "table",
  displayTableCell: "table-cell",
  displayTableRow: "table-row",
  displayCaption: "caption",

  displaySmNone: "sm:hidden",
  displaySmBlock: "sm:block",
  displaySmInline: "sm:inline",
  displaySmInlineBlock: "sm:inline-block",
  displaySmFlex: "sm:flex",
  displaySmInlineFlex: "sm:inline-flex",
  displaySmGrid: "sm:grid",
  displaySmInlineGrid: "sm:inline-grid",
  displaySmTable: "sm:table",
  displaySmTableCell: "sm:table-cell",
  displaySmTableRow: "sm:table-row",
  displaySmCaption: "sm:caption",

  displayMdNone: "md:hidden",
  displayMdBlock: "md:block",
  displayMdInline: "md:inline",
  displayMdInlineBlock: "md:inline-block",
  displayMdFlex: "md:flex",
  displayMdInlineFlex: "md:inline-flex",
  displayMdGrid: "md:grid",
  displayMdInlineGrid: "md:inline-grid",
  displayMdTable: "md:table",
  displayMdTableCell: "md:table-cell",
  displayMdTableRow: "md:table-row",
  displayMdCaption: "md:caption",

  displayLgNone: "lg:hidden",
  displayLgBlock: "lg:block",
  displayLgInline: "lg:inline",
  displayLgInlineBlock: "lg:inline-block",
  displayLgFlex: "lg:flex",
  displayLgInlineFlex: "lg:inline-flex",
  displayLgGrid: "lg:grid",
  displayLgInlineGrid: "lg:inline-grid",
  displayLgTable: "lg:table",
  displayLgTableCell: "lg:table-cell",
  displayLgTableRow: "lg:table-row",
  displayLgCaption: "lg:caption",
};
