export const sizes = [
  "2xs",
  "xs",
  "sm",
  "lg",
  "xl",
  "2xl",
  "1x",
  "2x",
  "3x",
  "4x",
  "5x",
  "6x",
  "7x",
  "8x",
  "9x",
  "10x",
];

export const fontSizes = {
  xs: ["12px", "1.5"],
  sm: ["16px", "1.5"],
  md: ["20px", "1.6"],
  lg: ["24px", "1.6"],
  xl: ["28px", "1.7"],
  xxl: ["32px", "1.7"],
  "3xl": ["36px", "1.8"],
  "4xl": ["40px", "1.8"],
  "5xl": ["44px", "2.0"],
  "6xl": ["48px", "2.0"],
  "7xl": ["52px", "2.1"],
  "8xl": ["56px", "2.1"],
  "9xl": ["64px", "2.2"],
}

export const fontSizeMap: { [key: string]: { [size: string]: string } } = {
  sm: {
    h1: "text-4xl leading-tight",
    h2: "text-3xl leading-tight",
    h3: "text-2xl leading-tight",
    h4: "text-xl leading-tight",
    h5: "text-lg leading-tight",
    h6: "text-lg leading-tight",
    p: "text-sm leading-tight",
    body: "text-sm leading-tight",
    label: "text-xs leading-tight",
    small: "text-xs leading-tight",
  },
  md: {
    h1: "text-5xl leading-snug",
    h2: "text-4xl leading-snug",
    h3: "text-3xl leading-snug",
    h4: "text-2xl leading-snug",
    h5: "text-xl leading-snug",
    h6: "text-lg leading-snug",
    p: "text-base leading-snug",
    body: "text-base leading-snug",
    label: "text-sm leading-snug",
    small: "text-sm leading-snug",
  },
  lg: {
    h1: "text-6xl leading-normal",
    h2: "text-5xl leading-normal",
    h3: "text-4xl leading-normal",
    h4: "text-3xl leading-normal",
    h5: "text-2xl leading-normal",
    h6: "text-xl leading-normal",
    p: "text-lg leading-normal",
    body: "text-lg leading-normal",
    label: "text-base leading-normal",
    small: "text-base leading-normal",
  },
  xl: {
    h1: "text-7xl leading-relaxed",
    h2: "text-6xl leading-relaxed",
    h3: "text-5xl leading-relaxed",
    h4: "text-4xl leading-relaxed",
    h5: "text-3xl leading-relaxed",
    h6: "text-2xl leading-relaxed",
    p: "text-xl leading-relaxed",
    body: "text-xl leading-relaxed",
    label: "text-lg leading-relaxed",
    small: "text-lg leading-relaxed",
  }
};


